In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv("Data.csv")

In [6]:
dataset.head(20)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [78]:
X = dataset.iloc[:,:-1].values

In [79]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [80]:
Y = dataset.iloc[:,-1].values

In [81]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'], dtype=object)

In [82]:

#Missing Data
from sklearn.preprocessing import Imputer

In [83]:
impt = Imputer(missing_values='NaN',strategy='mean',axis=0)

In [84]:
imputer = impt.fit(X[:,1:3])

In [85]:
X[:,1:3] = imputer.transform(X[:,1:3])

In [86]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [91]:
#Categorical Data
from sklearn.preprocessing import LabelEncoder

In [92]:
labelEncoder_X = LabelEncoder()

In [93]:
LabelEncoder?

In [94]:
X[:,0] = labelEncoder_X.fit_transform(X[:,0])

In [95]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [105]:
labelEncoder_Y = LabelEncoder()

In [106]:
Y = labelEncoder_Y.fit_transform(Y)

In [107]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [96]:
#Dummy Variable
from sklearn.preprocessing import OneHotEncoder

In [97]:
oneHot = OneHotEncoder(categorical_features=[0])

In [98]:
OneHotEncoder?

In [108]:
X = oneHot.fit_transform(X).toarray()

In [104]:
X_data.head()

0    1    2     3             4
0  1.0  0.0  0.0  44.0  72000.000000
1  0.0  0.0  1.0  27.0  48000.000000
2  0.0  1.0  0.0  30.0  54000.000000
3  0.0  0.0  1.0  38.0  61000.000000
4  0.0  1.0  0.0  40.0  63777.777778

In [110]:
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.40000000e+01,   7.20000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.70000000e+01,   4.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          3.00000000e+01,   5.40000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.80000000e+01,   6.10000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          4.00000000e+01,   6.37777778e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.50000000e+01,   5.80000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.87777778e+01,   5.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.80000000e+01,   7.90000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          5.00000000e+01,   8.30000000e+04],
       [  1.00000000e+00,   0.0000000

In [109]:
#train-test spliting
from sklearn.cross_validation import train_test_split

In [112]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [111]:
train_test_split?

In [115]:
Y_train,Y_test

(array([1, 1, 1, 0, 1, 0, 0, 1]), array([0, 0]))

In [116]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

In [117]:
sc_X = StandardScaler()

In [118]:
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [119]:
X_train, X_test

(array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
        [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
        [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
        [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
        [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
        [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
        [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
        [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]]),
 array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
        [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]]))